### ISSUE TITLE
A question about configs.py.sample

### ISSUE THREAD

**Issue by SepehrRasouli** [onionj/pybotnet#22]
Hi, Onionj.
 I've read your **Persian** documentation and i noticed that you said the delay should not be less than 10. why?  and why you haven't write the same for the **English** documentation? Because the delay in the README.MD version of configs.py.sample has a delay of **7** seconds and the delay in the original **configs.py.sample** code has a delay of **10** seconds. 
What are your thoughts ? How can we fix this ?
SepehrRS.

**Comment by onionj** [comment]
hi my friend 
Because we use a 3rd party proxy and it possible that the proxy will block the IP, I set the number high to reduce the risk 
But recently i refactor the code and removed the extra connections, and it seemed logical to reduce this number as well.

Persian document has not been updated for a long time ...!
And in the new version we need an have an English document that covers everything !!

**Comment by SepehrRasouli** [comment]
Thank you very much !

**Comment by onionj** [comment]
YW :D
